---
- name: to install docker in all servers
  hosts: all
  tasks:
    - name: to download shell script
      shell:  curl -fsSL https://get.docker.com -o install-docker.sh
    - name: to run shell script
      shell: sudo sh install-docker.sh
...
